spring:
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}'
    username: '${DB_USER}'
    password: '${ASECA_PASSWORD}'

server:
  servlet:
    context-path: '/api'
  error:
    include-message: always